### ISSUE TITLE
Tous niveaux / Si je mets le mode plein écran dans safari sur Ipad ça me gêne pour interagir avec des gestes haut-bas car l’écran bouge en même temps

### ISSUE THREAD

**Issue by louije** [louije/bestiorobot#2]

**Comment by louije** [comment]
@ZoeAegerter qu’est-ce que tu appelles le mode plein écran ?

**Comment by louije** [comment]
J'ai réglé pour que, quand on fasse "ajouter à l'écran d'accueil", ça marche beaucoup mieux maintenant. Aussi mis une icône qu'on pourrait revoir.

**Comment by ZoeAegerter** [comment]
coool, ça marche hyper bien ^^

**Comment by ZoeAegerter** [comment]
et tu as réussi à gérer les marges du niveau 1, ça rend super ;)

**Comment by ZoeAegerter** [comment]
zut par contre je peux pas dessiner au doigt car l'écran "bouge", il suit mon doigt, tu vois ce que je veux dire ?

**Comment by louije** [comment]
euh non mais on peut s’appeler ! c’est quel niveau / etc ?

**Comment by ZoeAegerter** [comment]
bin tous en fait, mais il y a peut-être un truc que j'ai pas capté :) on peut s'appeler avant 14h ou demain à l'heure du dej !
